// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    seed: "tsx prisma/seed.ts",
  },
  datasource: {
    // A integração Neon da Vercel cria a variável com o nome prefixado pelo
    // recurso (ex: Pomosul_DATABASE_URL_UNPOOLED) em vez de DATABASE_URL.
    url: process.env["DATABASE_URL"] ?? process.env["Pomosul_DATABASE_URL_UNPOOLED"],
  },
});
